import { Component } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import i18n from '../i18n';

import FunctionComponent from './FunctionComponent';
import LegacyComponentClass from './ClassComponent';

class HomeClass extends Component {
    static async getInitialProps({ ctx }) {
        console.log('HomeClass.getInitialProps()')
            return { count: 0 }
      }

      render () {
        const locale = 'en'
        if (i18n.language !== locale) {
            i18n.changeLanguage(locale)
        }
        return (
          <div className={styles.container}>
            <LegacyComponentClass />
            <FunctionComponent />
            <a href="/home-function">home-function</a>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
      
            <main className={styles.main}>
              <h1 className={styles.title}>
                Welcome to <a href="https://nextjs.org">Class</a>
              </h1>
      
              <p className={styles.description}>
                Get started by editing{' '}
                <code className={styles.code}>pages/index.js</code>
              </p>
      
              <div className={styles.grid}>
                <a href="https://nextjs.org/docs" className={styles.card}>
                  <h2>Documentation &rarr;</h2>
                  <p>Find in-depth information about Next.js features and API.</p>
                </a>
      
                <a href="https://nextjs.org/learn" className={styles.card}>
                  <h2>Learn &rarr;</h2>
                  <p>Learn about Next.js in an interactive course with quizzes!</p>
                </a>
      
                <a
                  href="https://github.com/vercel/next.js/tree/master/examples"
                  className={styles.card}
                >
                  <h2>Examples &rarr;</h2>
                  <p>Discover and deploy boilerplate example Next.js projects.</p>
                </a>
      
                <a
                  href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  className={styles.card}
                >
                  <h2>Deploy &rarr;</h2>
                  <p>
                    Instantly deploy your Next.js site to a public URL with Vercel.
                  </p>
                </a>
              </div>
            </main>
      
          </div>
        )
    }
}
export default HomeClass